### ISSUE TITLE
Quick Question (no issue...)

### ISSUE THREAD

**Issue by sgrzy01** [OpenVPN/openvpn3-indicator#19]
Sorry.. I did attempt to find this myself, but where does the indicator store its config… I want to try to reorder the connection list and hope I can just edit a file to do that.

Thanks!.

**Comment by dsommers** [comment]
It's stored in the OpenVPN 3 Configuration Manager service.

To reorder the list you currently need to export/dump it (`openvpn3 config-dump`) to a file and re-import it.

**Comment by grzegorz-gutowski** [comment]
Indicator does not store any configuration.
When there are more than one concurrent session, then the indicators are sorted by:
`{config_name}-{session_id}`
The configs in the drop-down list are sorted by:
`{config_name}`

So, the only way to change the order is to assign names to the configurations so that they are sorted (alphabetic order) in your favorite way.

**Comment by sgrzy01** [comment]
Got it.. all good! Thanks for quick reply.

**Comment by dsommers** [comment]
Btw .... you can rename config profiles using `openvpn3 config-manage --rename` ... More details in the [openvpn3-config-manage man page](https://codeberg.org/OpenVPN/openvpn3-linux/src/branch/master/docs/man/openvpn3-config-manage.1.rst).
